name: update terraftom module
description: used to create a terrafrom module in an organization
inputs:
  token:
    description: terraform user token user
    required: true
  module_name:
    description: the name of the terraform module to be created create
    required: true
  provider:
    description: the module provider | aws
    required: true
  registry_name:
    description: private | public registry
    required: true
  organization:
    description: >-
      the terrafrom cloud organization to have the module created in | your team
      organization
    required: true
  version:
    description: the terrafrom module uploaded | updated version
    required: true
  file_path:
    description: the module compressed file path (file must be with extention tar.gz)
    required: true
outputs:
  response:
    description: request returned response or error
runs:
  using: node14
  main: dist/index.js
