on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test function
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: tets create module
        id: hello
        uses: hayaah/update-terrafrom-cloud-module@v1.1.7
        with:
          module_name: 'module-Name-100'
          token:  ${{ secrets.TERRAFORM_TOKEN }}
          provider: 'aws'
          registry_name: 'private'
          organization: 'wix-infragod'
          version: 3.0.2
          file_path: ${{ github.workspace }}/Archive.zip
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.response }}"