name: Publish new release of create terrafrom module custom action
on:
  release:
    types: [published, edited]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
          
      - name: Setup Node
        uses: actions/setup-node@v2
       - uses: JasonEtco/build-and-tag-action@v2
        with:
          tag_name: ${{ steps.releaser.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ github.token }}