on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

name: Upload Release Asset

jobs:
  set-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.push-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: push-tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - run: echo "${{ steps.push-tag.outputs.tag }}"
        
  set-release:
    name: build dist folders
    runs-on: ubuntu-latest
    needs: 
     - set-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build actions
        run: | 
          cd ./actions
          npm install
          npm run build
          ls
      - name: build actions-2
        run: | 
          cd ./actions-2
          npm install
          npm run build
          ls
      - run: |
          cd ./actions-2
          ls
      
      - run: |
          zip -r actions.zip  actions/dist/** actions-2/dist/**
          ls
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.set-tag.outputs.tag }}
          release_name: Release System Dev
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ${{ github.workspace }}/actions.zip
          asset_name: actions.zip
          asset_content_type: application/zip

 
